### ISSUE TITLE
[bug]这个网址打不开啊…

### ISSUE THREAD

**Issue by cheny0y0** [Cytoid/Cytoid#101]
wiki中的网址：<http://cytoid.io/browse>打不开

**Comment by Teages** [comment]
这个是旧的, 新的网站是
cn: http://cytoid.cn/levels
others: http://cytoid.io/levels

**Comment by cheny0y0** [comment]
> 这个是旧的, 新的网站是
> cn: http://cytoid.cn/levels
> others: http://cytoid.io/levels

<http://cytoid.io/browse/io.cytoid.glow_dance> 这个也打不开

**Comment by Teages** [comment]
... 既然browse改成了level,那别的当然也要改啊...

另外, 这个问题与Cytoid游戏本体无关, 请到玩家讨论区询问.

因此, 建议把另一个issue也自行close掉.

**Comment by cheny0y0** [comment]
ok了
