### ISSUE TITLE
[Bug] Crash while startup at tutorial

### ISSUE THREAD

**Issue by rong-xiaoli** [Cytoid/Cytoid#114]
When I open the app, after delay adjusting and the tutorial, it crashes and after that, it repeats the process again. 

Device: iPad Air Gen.1
RAM: 1GB
iOS ver.: 12.5.4

(Maybe its RAM isn't enough?)

**Comment by Teages** [comment]
Sorry, but its RAM is not enough

**Comment by Teages** [comment]
https://github.com/Cytoid/Cytoid/issues/107#issuecomment-906205113

The minimum requirement is iPhone 7, which have 2GB RAM

**Comment by rong-xiaoli** [comment]
Thanks. Problem solved. It is okay to close it.

**Comment by Teages** [comment]
so close it
