### ISSUE TITLE
墙内请求帮助，打开项目会弹出以下报错

### ISSUE THREAD

**Issue by cjrsacred** [Cytoid/Cytoid#121]
<img width="305" alt="Screenshot 2021-12-16 231445" src="https://user-images.githubusercontent.com/32447555/146398853-8bbe7de0-5369-45ab-8716-abfdcbd7a7e9.png">
目前用v2rayN翻墙，但Unity看来起来不走系统代理的样子，照着Google设置环境变量也没用（应该是我设置的有问题），请求帮助

**Comment by baisebaoma** [comment]
尊敬的女士/先生 您好，
感谢您的来信。这是一封自动回复邮件，代表您的邮件已送达至我的邮箱。在我检查邮箱时，我会立即回复您。感谢您的等待。Baisebaoma

**Comment by Teages** [comment]
请不要发布无关commit, 这是节奏游戏 Cytoid 的代码存储仓库.

如果您在使用软件时发现问题, 请尝试联系该软件的官方人员.

**Comment by cjrsacred** [comment]
抱歉打扰了, 麻烦删掉这个issue
