### ISSUE TITLE
ToS is probably incompatible with GPL license

### ISSUE THREAD

**Issue by JacksonChen666** [Cytoid/Cytoid#122]
This is somewhat similar to the [audacity of Audacity](https://github.com/audacity/audacity/issues/1213), but probably without the audacity to do such a thing. Oh, and **I'm not a lawyer, this isn't legal advice, I'm citing other people without extended verification of truth, get a lawyer if you have *any* legal questions and not some random person on the internet.**

In the [English ToS on cytoid.io](https://cytoid.io/pages/terms), the following section:

> If you do not agree with any of these terms, you are prohibited from using or accessing Cytoid's services, **including the game client**, the CytoidIO website and its mirrors, or any affiliated services ("Cytoid").

contradicts with the following in the [LICENSE](https://github.com/Cytoid/Cytoid/blob/c921146814412df82e47424e67bd6f9238f7259e/LICENSE#L154-L177) file (GPLv3 section 2):

> conditions are met.  **This License explicitly affirms your unlimited**
> **permission to run the unmodified Program.**  The output from running a

Comments related to incompatibility with the GPL license and privacy policy with Audacity:
- https://github.com/audacity/audacity/issues/1213#issuecomment-873536190
- https://github.com/audacity/audacity/issues/1213#issuecomment-873484518

**Comment by Teages** [comment]
See [.gitignore](https://github.com/TigerHix/Cytoid/blob/main/.gitignore), the Cytoid published in AppStore/Google Play is not a real unmodified program. Some code about Cytoid Services is not included.

Maybe it can explain these.

**Comment by TigerHix** [comment]
Hi, thank you for your concern. As @Teages correctly pointed out, this repository contains **partial source code and assets** (more specifically, most source code excluding cytoid.io related authorization/verification and assets excluding any official levels/characters/etc) of the binary released in Google Play & App Store. In other words, you may use and extend this repo based on GPLv3 license, but the app store binaries, as of now, are proprietary and require compliance with our ToS and privacy policy as stated on https://cytoid.io.

**Comment by JacksonChen666** [comment]
Ah, I see.
