### ISSUE TITLE
Collections need critical fixes

### ISSUE THREAD

**Issue by BentuxTheCow** [Cytoid/Cytoid#126]
Collections are, for lack of better words, a goddamn mess.

### Current situation:
Website:
- Cannot search for collections as one can search for individual levels. Renders collection tags redundant.
- Access to "all collections" is only possible from "Home" tab. (i.e. Missing "Collections" tab in the top ribbon.)
- Cannot view "all collections [profile] has created" as one can view "all levels [profile] has uploaded". 
- "View all N (collections)" button in user profile is inoperative.

In-game:
- No way to view, edit, or otherwise interact with collections without leaving the Cytoid app.

### Problems:
- Organisation and stocktaking for a large number of collections is extremely troublesome.
- Old collections are so difficult to find so as to be practically inaccessible.
- Users disincentivised from using collections.

### Proposal:
Website:
- Add a "Collections" tab to the top ribbon that points to [https://cytoid.io/collections](https://cytoid.io/collections).
- Implement search bar for collections accessible when in the "Collections" tab. 
- Update website architecture to support filtering collections by uploader, e.g. by https://cytoid.io/collections?owner=[user], such that "View all N (collections)" button has a valid link to point to.

In-game:
- Implementation may or may not be practical and/or necessary - it may be fine to keep collections as a website-exclusive feature.

### Personal anecdote (with potentially great impropriety):
As things stand, collections are so hidden away that there is little reason to use them as anything more than folders into which levels are slotted for archival purposes, and even then they are easily lost folders since they cannot be searched for. If implemented properly, collections could feasibly be used as a playlist feature for players to curate their favourite charts, and as an effective organisation tool or even as storybooks for (more experienced and ambitious) creators. 

I am very disappointed with how collections are. I am a part of Cy7, a charter group, which makes heavy use of collections to organise released charts. This is a necessary measure, as we release tens of charts which vary greatly in theming and may have stories woven into them. We then face problems such as being unable to identify quickly whether level A1 and level A2 belong to different anime OST collections. Even on my own, I find myself discouraged from creating themed collections as they give me no further publicity while the collections do not improve my organisation.

Please, fix the damn website.

**Comment by Teages** [comment]
I agree, This haven't been updated for at least three years. But we have so many other problems need to fix so would not work for it lately (date by year)...

but I do think these can be solved with "tags" function, improve the search precision of tags is also a solution. (At least our neighbor use tags more than packs)

**Comment by Teages** [comment]
> view all collections by [user]

I order it, check the progress after a month. If there is no progress, you can bomb my discord

**Comment by Teages** [comment]
I think it is resolved
