### ISSUE TITLE
It is recommended to replace the game engine.

### ISSUE THREAD

**Issue by scilxurkel001** [Cytoid/Cytoid#140]
Since Unity has changed its charging policy, it is recommended to replace the game engine.

According to the style of the game, it is recommended to switch to Cocos2D or Godot2D.

I know that code porting is very difficult, but I don't want you to pay extra for more than 200,000 installations.

**Comment by Teages** [comment]
Appreciate your concern! 
Our total revenue is 0, so it is unnecessary.
