### ISSUE TITLE
Console error on iOS 

### ISSUE THREAD

**Issue by cooolius** [Cytoid/Cytoid#142]
Hi I just downloaded cytoid and I’m greeted with a black screen and some code. If anyone could help me I would be super happy

btw I’m using an iPhone 8 with iOS 16.7.2

**Comment by Teages** [comment]
you can get help from our official discord 
https://discord.gg/cytoid

**Comment by cooolius** [comment]
I don’t have dc

**Comment by Teages** [comment]
can you post the screenshot about the error here, so that I can provide more help for you?

**Comment by cooolius** [comment]
Ok

**Comment by cooolius** [comment]
![IMG_1579](https://github.com/Cytoid/Cytoid/assets/151452318/7540edb8-384d-49e6-8b2e-d9d5bab47dec)
![IMG_1580](https://github.com/Cytoid/Cytoid/assets/151452318/ddda1849-e976-4e2d-bccc-c67c52b88636)

**Comment by Teages** [comment]
Try to change phone language to English then launch the game
You can change your language back after calibrating

We will fix it in the next release

**Comment by cooolius** [comment]
Thx
Imma try that out

**Comment by cooolius** [comment]
Thx it worked
