### ISSUE TITLE
Hyper and another mods health bar should recover with cleared notes like in Osu! and other rhythm games

### ISSUE THREAD

**Issue by LJW21-GitHub** [Cytoid/Cytoid#148]
Hyper and Another are so annoying rn because they do not recover with cleared notes, so you can like choke at the beginning of the map, survive all the map at the edge of the death and die because of 1 random miss...

Health bars would be fairer with recovering system, like every other rhythm games

**Comment by Teages** [comment]
it has a recover: https://cytoid.wiki/en/reference/game/mods#hyper

fell free to talk about it in our [Discord Channel](https://discord.com/channels/362884768498712579/362893769714171904) if you think that is too hard.
