### ISSUE TITLE
Is it really possible to build the project by myself ? 

### ISSUE THREAD

**Issue by anise0x7c** [Cytoid/Cytoid#149]
Cytoid crashes frequently on my own device. I wonder if I could build the apk of the game by my own to solve this.

But there are tons of gitignored  files and some plugins are paid. It's no doubt that there will be hundreds of errors if I just simply import the repository into Unity. (And it actually does)

So I really hope if someone could help me how to do or is it possible to do so 🥲

**Comment by Thanh9356** [comment]
Sorry but, this is more likely a question than an issue.

**You can't build this project by yourself without any modification.**

You need to have a few Unity add-ons, also a security key (?), and many other stuffs. Here is why you have to check and remove yourself.

**Comment by anise0x7c** [comment]
Alright I understand, and im quite sorry that I put this question at a wrong place, I will close this.
