### ISSUE TITLE
Cytoid加载完UnityLogo后崩溃

### ISSUE THREAD

**Issue by Rika1990** [Cytoid/Cytoid#150]
两台设备，一台OPPO A31T,Android5.1,Armeabi-v7a,从Googleplay商店下载，一台雷电模拟器，Android9，都出现了打开Cytoid加载完unity图标后花屏卡死的情况，原因未知

**Comment by Neo-Zhixing** [comment]
ok but it's also a phone released in 2015, almost 10 years ago

**Comment by Teages** [comment]
我们没有继续支持arm32的计划，cytoid也不支持在模拟器中游玩
