### ISSUE TITLE
Outer circle does not enlarge 外圈不放大

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/Cytoid#41]

**Comment by gfsd20433** [comment]
how about mod for no inner circle and outer circle 23333

**Comment by gfsd20433** [comment]
i mean no color for those circles

**Comment by TigerHix** [comment]
（思考）

主要我现在渲染層的代碼寫超亂 要寫的模塊化一點才好實現這些mod orz

**Comment by TigerHix** [comment]
Hmmmm 可能直接引入 skins 会比较好
