### ISSUE TITLE
Auto-pause when notifications/phone calls arrive does not pause music

### ISSUE THREAD

**Issue by TigerHix** [Cytoid/Cytoid#54]
On Android.

**Comment by gfsd20433** [comment]
that pause >___>
Pause isnt often been used because the music wont sync to note after resume the game.
it is better to retry when being disturbed >__>

**Comment by TigerHix** [comment]
<_< Definitely true. Adding it as another issue

**Comment by TigerHix** [comment]
Should be fixed in 2.0.
