### ISSUE TITLE
Adjustable Judgment 可调整判定

### ISSUE THREAD

**Issue by PretTy-Fish** [Cytoid/Cytoid#57]
Create a page that can be entered from "Option" page which allows the player to adjust the judgment for relaxation or extra challenge. Also, put a "Reset" button on that page to reset the judgment to the default.
在设置页面下建立一个调整判定的子页面以让玩家自行调整判定，来达到放松或者挑战自己的目的。同时在该页面下放置一个Reset（重置）按钮以重置判定至默认判定。

The score should be recorded only when it is at the default judgment for fairness. When the judgment is adjusted, the score will not be recorded and a notice of "UNSCORED" will be shown at the top of the screen (like the "UNRANKED" notice in osu!).
为了公平起见，只有在默认判定下才记录分数。当判定被调整过时，分数不会被记录，以及在打歌的时候顶端应放置一个“UNSCORED”字样（跟osu!里的“UNRANKED”字样类似）。

**Comment by TigerHix** [comment]
Added adjustable hitboxes.
