### ISSUE TITLE
占坑

### ISSUE THREAD

**Issue by ClassicOldSong** [Cytoid/Cytoid#64]
发现 Cytoid 后我又燃起了写制作网页版谱面编辑器的激情，特此占坑：
 https://github.com/ClassicOldSong/Cytloid
BTW Cytoid 现在的UI感觉比较蛋疼，选择歌曲的时候不是很舒服，有空我可能会画一个UI设计稿出来（又是一个大坑23333

**Comment by ZeroAurora** [comment]
挖坟（滑稽

**Comment by ClassicOldSong** [comment]
最近公司事情比较多。。。可能得再拖一段时间了。。。

**Comment by TigerHix** [comment]
慢慢来23333 我回复这个贴都用了八个月（不是

**Comment by brenthmiras** [comment]
With the web based cytoidlevel player, I am concerned with browser support.

**Comment by ZeroAurora** [comment]
两年前力（

**Comment by ClassicOldSong** [comment]
太忙了。。。前几个月离职了，准备回家创业，恐怕更忙了。。。。。。

**Comment by ClassicOldSong** [comment]
（然后我还被踢出了QQ群（x

**Comment by ZeroAurora** [comment]
@ClassicOldSong 
群这里事把三个月以上没发言的踢了呢（
没事，慢慢来，创业加油啊（

**Comment by ClassicOldSong** [comment]
多谢~

**Comment by TigerHix** [comment]
重新开坑的时候喊我233

**Comment by Neo-Zhixing** [comment]
这就是 时间磨平了棱角吧
2017年我还在上高中滑稽

**Comment by ClassicOldSong** [comment]
（我的公司已经开起来了（x
说来滑稽，现在做的东西跟游戏也有很大的关联（x

**Comment by ZeroAurora** [comment]
> （我的公司已经开起来了（x

congrats!!11
