### ISSUE TITLE
web based cytoidlevel player

### ISSUE THREAD

**Issue by brenthmiras** [Cytoid/Cytoid#72]
I have seen some players embed their recording of their charts in the description.
I think it would be better if there is a web based player that reads the cytoidlevel so that chart makers can make it easy to show a preview of their charts without downloading and playing the level in cytoid.

**Comment by ClassicOldSong** [comment]
This could be realised by Cytloid iff it could be done..
https://github.com/TigerHix/Cytoid/issues/64

**Comment by TigerHix** [comment]
[CytoidPlayer](https://sites.google.com/site/cytoidcommunity/guides/chart-previewers?authuser=0) is now available.
