### ISSUE TITLE
Can't install CytoidLevel

### ISSUE THREAD

**Issue by 78Alpha** [Cytoid/Cytoid#80]
After installing from Google play I attempted to install a cytoidlevel file, however, it states that there is no app to install the file. After reinstalling the game, the issue still persists. However, it left an u removable icon on my app screen (I assume it tried to treat a level like an app).

TL;DR

Can't install cytoidlevel, no app association.

**Comment by return215** [comment]
There is an alternative to install (load) Cytoid levels. Just copy the `.cytoidlevel` file(s) to Cytoid folder, open the game, and the levels will be loaded automatically.

I also have the same problem here using your method. Android doesn't recognize the `.cytoidlevel` file format. But, I can install the levels with no problems using FX file explorer (open the file using Cytoid). The option is shown there but not on Android.

**Comment by p1ho** [comment]
Is there a more elegant way of doing this? What if we implement an in-game song browser (wrapper for [cytoid.io levels](https://cytoid.io/levels) and make it download file to the `Cytoid` folder directly (since the app should have privilege) , then we just simply refresh the menu after the download finished.

**Comment by TigerHix** [comment]
@p1ho In-game browsing & downloading is implemented in the 2.0 version (develop branch) which will hopefully release in March. The traditional way of installing .cytoidlevels locally will still be supported. See https://twitter.com/TigerHixTang/status/1214996129282019329
