### ISSUE TITLE
能不能增加更详细的延迟调节

### ISSUE THREAD

**Issue by laoqijun** [Cytoid/Cytoid#81]
现在的延时还是只能玩玩以后自己在铺面设置准确数值
我希望能像arcaea那样让用户根据一段音乐节奏点击下来确定延迟比较好。
![Screenshot_20190426-093415_Cytoid](https://user-images.githubusercontent.com/32598564/56779439-967abb00-680d-11e9-8eb5-70ad8a9819b9.png)

**Comment by TigerHix** [comment]
Added in 2.0!
