### ISSUE TITLE
Sleek Render is off the Asset Store

### ISSUE THREAD

**Issue by colejd** [Cytoid/Cytoid#86]
Hi!

Sleek Render is no longer available for purchase: https://assetstore.unity.com/packages/vfx/shaders/fullscreen-camera-effects/sleek-render-mobile-post-processing-stack-103628

This makes it impossible for others to contribute until a replacement is found.

Thanks!

**Comment by TigerHix** [comment]
Sleek Render is removed from 2.0 (develop branch). We will set up a more detailed/helpful contributing guide once it's out as well!
