### ISSUE TITLE
Music out of sync with notes when headphone plugged in at launch

### ISSUE THREAD

**Issue by danielzgtg** [Cytoid/Cytoid#87]
The music plays 100x slower than the notes and is really distorted. This happens when I have my headphones plugged in when opening the game. I am using a OnePlus 7 Pro (Android 10 Beta 5) with the Apple USB-C Headphone Adapter. Oddly, the problem disappears if I force quit Cytoid (1.5.2), unplug my headphones, reopen it (music is normal now), and then plug my headphones back in (music stays normal).

This problem also occurs when I switch apps away from and back to the game. In that case, the problem randomly occurs if my headphones are plugged in, but never when they are unplugged.

**Comment by Teages** [comment]
Just try to replay the game after you have a break.(This problem seems hard to solve,and Tigertix is busy in developing Cytoid 2.0 so problem would not be solved soon.)But why not update your Android version to the stable one?

**Comment by danielzgtg** [comment]
I'm on Beta 6 now. OxygenOS Beta 6 is newer than the stable one so I can't downgrade. However, it probably happens on the stable version too.

**Comment by Teages** [comment]
> I'm on Beta 6 now. OxygenOS Beta 6 is newer than the stable one so I can't downgrade. However, it probably happens on the stable version too.

Sorry to hear that.It seems that Cytoid2.0 is a rebuild version for Cytoid.The problem may be fix after Cytoid2.0.Maybe you can try Cytoid2.0(MAYBE NEVER PUBLIC.:( ).

**Comment by TigerHix** [comment]
This seems like a problem with low-level Unity/Android drivers and I am not sure if that's fixable. When 2.0 comes out around mid-March, please let me know if this issue has resolved for you. Thanks!

**Comment by danielzgtg** [comment]
I wonder if updating Unity would fix this. The README asks for 2018.2.12 while 2018.4.6, 2018.4.9 and 2019.1.0 might all contain fixes (looking for "Android" and "audio" in the changelogs)

**Comment by TigerHix** [comment]
Should be fixed in 2.0. A new setting "Headset note offset" was added as well.
