### ISSUE TITLE
many errors 

### ISSUE THREAD

**Issue by muafakul** [Cytoid/Cytoid#88]
![image](https://user-images.githubusercontent.com/13078369/71461732-727bd900-27e3-11ea-9bc4-c79964ad0085.png)

**Comment by TigerHix** [comment]
Please see .gitignore for a list of assets you need to import from the Asset Store, or you can manually unlink them from code.

I plan to improve this situation in future releases.

**Comment by muafakul** [comment]
how to unlink them from the code , i just want to know how you make the button that when we click , then ripple animation appear
