### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by jp-jp-123** [Cytoid/Cytoid#89]
![Screenshot_20200101-211708](https://user-images.githubusercontent.com/59426790/71649856-fcc8bd80-2d4c-11ea-9f33-33f8131eb294.jpg)
whenever i try to use the chart i created on Cytunity, it shows this error after trying to load the audio, i tried also to email the dev but haven't yet responded. I'm so frustrated that i can't play it asap since i can't find this song on cytoid.io

**Comment by TigerHix** [comment]
It looks like your chart is invalid. Come to our [Discord](https://discord.gg/cytoid) for charting-related help!
