### ISSUE TITLE
Difficulty differences in 15+ charts

### ISSUE THREAD

**Issue by 2394425147** [Cytoid/Cytoid#90]
As the title states, some 15+ charts might be extremely hard but some others might be just a bit above 15, but (iirc) they give players the same amount of rt growth, which I think is unfair. So is it possible to add more difficulty options while not giving charters the chance to falsely label it?

**Comment by TigerHix** [comment]
The "16" and "16+" difficulties (and probably more) will be unlocked later this year. Back in when Cytoid 1.5 is released we didn't have enough quality charts in the 15+ range, which is why we set the upper limit at 15. This will hopefully change soon.
