### ISSUE TITLE
New pause algorithm?

### ISSUE THREAD

**Issue by 2394425147** [Cytoid/Cytoid#91]
Basically works like this:
(Player pauses)
Get the last clicked note and then use that note's id to find out the next note (Like "nextNote", for example").
Then get the page which the nextNote is in, when player unpauses, go to a few pages back (I think a bar (4 beats)) and **don't** render the notes which have their note id smaller than nextNote.id.
In this way we can also set the audio position to a few seconds before to match the game.

Hopefully this works!

**Comment by TigerHix** [comment]
This mechanism is a little bit problematic in the sense that people will start pausing repetitively throughout the "stamina" sections to rest and gain an unfair advantage to those who don't pause.
