### ISSUE TITLE
Upload level error 上传关卡错误

### ISSUE THREAD

**Issue by Rabpet** [Cytoid/Cytoid#93]
上传关卡的时候经常发生错误提示"can not parse level.json"，这个levels.json文件我试了很多方法编辑都没有用，Notepad++也用了，还是不行，总是不能上传成功。问题出在哪里？
While uploading, a error called "can not parse level.json" always happens. I tried many ways but failed to solve the problem. I have used Notepad++ to edit the json file but still failed. What is the problem?

**Comment by TigerHix** [comment]
Encoding 有没有设置 UTF-8 without BOM? 另外这个issue应该发去 Cytoid/cytoid.io~
