### ISSUE TITLE
游戏时报错

### ISSUE THREAD

**Issue by Aaron2412** [Cytoid/Cytoid#96]
有一些铺面游玩的时候会报错：
`
Cannot generate 9 slice most likely because the size is too big. Requires 2147483647 vertices and 2147483647 indices

UnityEngine.SpriteRenderer:set_size(Vector2)
Cytus2.Views.HoldNoteView:OnLateUpdate()
Cytus2.Models.HoldNote:LateUpdate()
`
请问这是铺面的锅还是游戏对锅？

**Comment by Teages** [comment]
谱面有链接嘛，可以发出来看看？

**Comment by Aaron2412** [comment]
> 谱面有链接嘛，可以发出来看看？

https://cytoid.io/browse/cytoid.nhelv.rlyo
https://cytoid.io/levels/face.corruption
自己玩就有，Auto不会出现

**Comment by TigerHix** [comment]
暂时没在 2.0 中发现，先 close 了。
