### ISSUE TITLE
Audio issues (Speed, crackling)

### ISSUE THREAD

**Issue by RubberDuckShobe** [Cytoid/Cytoid#97]
The audio is slow and has lots of crackling in it. Frame rate/performance is definitely not the issue here, it's 83FPS on average.

Device: OnePlus 7T (HD1903)
Android version: Android 10, OxygenOS 10.0.9.HD65BA

**Comment by Teages** [comment]
Some device need to change DSP buffer size. In Cytoid 2.0, your problem should be fixed.

So, just wait for the comming version!
