### ISSUE TITLE
Issue about starting level

### ISSUE THREAD

**Issue by CahyaAziz** [Cytoid/Cytoid#98]
Hi i wanted to repor an issue when I tried to play any level the line just freeze where it apears (as shown in the picture) and no notes are showing either. I hope to hear from developers about this problem thank you (PS : im running IOS 10.3.4)

Image : https://www.dropbox.com/s/2loxa20e3efbmg9/IMG_9131.PNG?dl=0

**Comment by TigerHix** [comment]
Seems like an audio engine issue with old versions of Unity. Please try 2.0 which will be publicly available this Friday. If it still doesn't work for you let me know.
