### ISSUE TITLE
[Bug] Using medium quality on iPad Pro will cause a crash

### ISSUE THREAD

**Issue by lz233** [Cytoid/Cytoid#99]
Version: 2.0.0 (100)
Device: iPad Pro 2018 11-Inch (iPad 8,2)
[cytoid.log](https://github.com/Cytoid/Cytoid/files/5310818/cytoid.log)

**Comment by Teages** [comment]
2.0.2 tested？

**Comment by lz233** [comment]
tested. fixed.
